Repository elastic/docs-content, pull requests merged in 2024-07, with the labels that each got.

#30 Add custom roles page
  serverless/images/custom-roles-cluster-privileges.png
  serverless/images/custom-roles-index-privileges.png
  serverless/images/custom-roles-kibana-privileges.bak.png
  serverless/images/custom-roles-kibana-privileges.png
  serverless/images/custom-roles-ui.png
  serverless/nav/serverless-project-settings.docnav.json
  serverless/pages/custom-roles.mdx
  serverless/pages/project-settings.mdx
Labels: ci:doc-build

#41 Add Google Gemini connector
  serverless/pages/action-connectors.mdx
Labels: ci:doc-build

#40 Add custom roles to organization management
  serverless/images/individual-role.png
  serverless/pages/custom-roles.mdx
  serverless/pages/manage-access-to-org-user-roles.mdx
  serverless/pages/manage-access-to-org.mdx
Labels: ci:doc-build

#39 Replace references to text_expansion with sparse_vector
  serverless/pages/explore-your-data-ml-nlp-deploy-model.mdx
  serverless/pages/explore-your-data-ml-nlp-elser.mdx
  serverless/pages/search-your-data-semantic-search-elser.mdx
  serverless/pages/search-your-data-semantic-search.mdx
  serverless/partials/hybrid-search-elser.mdx
  serverless/partials/search-elser.mdx
Labels: ci:doc-build

#42 Fix link to APIs
  serverless/pages/apis-http-apis.mdx
Labels: ci:doc-build

#44 Fix 404 links to serverless API ref
  serverless/pages/clients-php-getting-started.mdx
  serverless/pages/developer-tools-troubleshooting.mdx
  serverless/pages/search-your-data-the-search-api.mdx
Labels: ci:doc-build

#45 Add pricing info everywhere
  serverless/pages/get-started.mdx
  serverless/pages/manage-billing-monitor-usage.mdx
  serverless/pages/manage-billing-pricing-model.mdx
  serverless/pages/manage-billing.mdx
  serverless/pages/pricing.mdx
  serverless/pages/sign-up.mdx
  serverless/partials/minimum-vcus-detail.mdx
Labels: documentation, ci:doc-build

#46 Add link to new CrowdStrike connector
  serverless/pages/action-connectors.mdx
Labels: enhancement, ci:doc-build

#48 Fix dev tools overview page typo #150
  serverless/pages/elasticsearch-developer-tools.mdx
Labels: documentation, ci:doc-build
