Repository elastic/docs-content, pull requests merged in 2024-06, with the labels that each got.

#15 Adds Discover help center article
  help-center/discover.mdx
  help-center/es-discover.mdx
  help-center/obs-discover.mdx
  help-center/sec-discover.mdx
Labels: documentation

#18 [Serverless] Add link to Cases connector
  serverless/pages/action-connectors.mdx
Labels: ci:doc-build

#29 Fix capitalization in management page titles
  serverless/pages/data-views.mdx
  serverless/pages/index-management.mdx
  serverless/pages/ingest-pipelines.mdx
  serverless/pages/logstash-pipelines.mdx
  serverless/pages/machine-learning.mdx
  serverless/pages/maintenance-windows.mdx
  serverless/pages/saved-objects.mdx
Labels: ci:doc-build

#34 Adds doc navs and landing pages
  es-help-center.docnav.json
  help-center/es-help-center.mdx
  help-center/obs-help-center.mdx
  help-center/sec-help-center.mdx
  obs-help-center.docnav.json
  sec-help-center.docnav.json
Labels: ci:doc-build

#35 Updates docs.elastic.co links to elastic.co/docs
  README.md
  serverless/pages/apis-http-apis.mdx
  serverless/pages/explore-your-data-visualize-your-data.mdx
  serverless/pages/integrations.mdx
  serverless/pages/manage-your-project-rest-api.mdx
  serverless/pages/sign-up.mdx
  serverless/pages/what-is-serverless.mdx
Labels: documentation, ci:doc-build
