Repository elastic/docs-content, pull requests merged in 2025-10, with the labels that each got.

#2823 ECK docs: adding note about component templates when using stack policies
  deploy-manage/deploy/cloud-on-k8s/elastic-stack-configuration-policies.md
Labels: bug

#3308 Replace diagram
  solutions/images/observability-apm-help-me-decide.png
  solutions/images/observability-apm-help-me-decide.svg
  solutions/observability/apm/apm-server/setup.md
Labels: documentation

#3253 Update DbVisualizer documentation images
  explore-analyze/images/elasticsearch-reference-dbvis-1-driver-manager.png
  explore-analyze/images/elasticsearch-reference-dbvis-2-driver-manager-elasticsearch.png
  explore-analyze/images/elasticsearch-reference-dbvis-3-driver-manager-download.png
  explore-analyze/images/elasticsearch-reference-dbvis-4-driver-manager-ready.png
  explore-analyze/images/elasticsearch-reference-dbvis-5-new-conn.png
  explore-analyze/images/elasticsearch-reference-dbvis-6-new-conn-elasticsearch.png
  explore-analyze/images/elasticsearch-reference-dbvis-7-new-conn-connect.png
  explore-analyze/images/elasticsearch-reference-dbvis-8-data.png
  explore-analyze/images/elasticsearch-reference-dbvis_add_connection.png
  explore-analyze/images/elasticsearch-reference-dbvis_add_db_connection.png
  explore-analyze/images/elasticsearch-reference-dbvis_connection_details.png
  explore-analyze/images/elasticsearch-reference-dbvis_hero.png
  explore-analyze/images/elasticsearch-reference-dbvis_new_driver_done.png
  explore-analyze/images/elasticsearch-reference-dbvis_new_driver_refresh.png
  explore-analyze/images/elasticsearch-reference-dbvis_new_driver_start.png
  explore-analyze/images/elasticsearch-reference-dbvis_open_driver_manager.png
  explore-analyze/query-filter/languages/sql-client-apps-dbvis.md
Labels: community

#3251 Adding screenshots to certain equivalent steps
  manage-data/images/elasticsearch-reference-tutorial-ilm-general-content-ingest.png
  manage-data/images/elasticsearch-reference-tutorial-ilm-rollover-general-content-create-policy.png
  manage-data/images/elasticsearch-reference-tutorial-ilm-rollover-general-content-create-template.png
  manage-data/lifecycle/index-lifecycle-management/tutorial-general-content-with-data-streams.md
Labels: Team:Admin

#3282 [Security] 9.0.8 release notes
  release-notes/elastic-security/index.md
Labels: release-notes

#3279 [Security] 9.1.5 release notes
  release-notes/elastic-security/index.md
  release-notes/elastic-security/known-issues.md
Labels: release-notes

#2864 Docs for mOTLP for ECH
  solutions/_snippets/edot-reference-arch.md
  solutions/images/ech-preview-motlp.png
  solutions/observability/apm/get-started.md
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
Labels: documentation

#3350 Small changes to S3 repo docs
  deploy-manage/tools/snapshot-and-restore/s3-repository.md
Labels: documentation

#3353 Fix link for serverless projects API
  explore-analyze/find-and-organize/saved-objects.md
Labels: Team:Experience
