Repository elastic/docs-content, pull requests merged in 2025-08, with the labels that each got.

#2347 Clarify bundle update content
  deploy-manage/deploy/elastic-cloud/upload-custom-plugins-bundles.md
Labels: documentation, supportability

#2216 Add a new section for transitioning indices to data streams
  manage-data/lifecycle/index-lifecycle-management/manage-existing-indices.md
  manage-data/lifecycle/index-lifecycle-management/tutorial-automate-rollover.md
Labels: documentation

#2443 Fixes typo in JWT token doc
  deploy-manage/users-roles/cluster-or-deployment-auth/jwt.md
Labels: documentation, v9.1.0, v9.0.1, Team:Admin, v9.2.0

#2422 [Security] 9.1.1 release notes
  release-notes/elastic-security/index.md
  release-notes/elastic-security/known-issues.md
Labels: release-notes

#2405 [Observability] Add Logs Essentials get started docs
  solutions/observability/get-started/logs-essentials.md
  solutions/toc.yml
Labels: documentation

#2461 Update 'ELSER on EIS' Limitations
  explore-analyze/elastic-inference/eis.md
Labels: v9.1.0

#2465 Add youtube video for file-based realm user authentiation
  deploy-manage/users-roles/cluster-or-deployment-auth/file-based.md
Labels: enhancement

#2495 Add kubestack troubleshooting
  troubleshoot/ingest/opentelemetry/edot-collector/insufficient-resources-kubestack.md
  troubleshoot/ingest/opentelemetry/toc.yml
Labels: documentation

#2512 [Security] 9.1.2 release notes
  release-notes/elastic-security/index.md
Labels: release-notes

#2557 Updating the info around the Kibana Docker image
  deploy-manage/deploy/self-managed/install-kibana-with-docker.md
  solutions/observability/apm/apm-server-binary.md
Labels: documentation

#2506 Adds Serverless changelog for August 4 and August 11
  release-notes/elastic-cloud-serverless/breaking-changes.md
  release-notes/elastic-cloud-serverless/index.md
Labels: release-notes

#2395 Clarify misleading CCS compatibility table
  deploy-manage/remote-clusters/_snippets/ccs-compatibility-table.md
  deploy-manage/remote-clusters/_snippets/remote-cluster-certificate-compatibility.md
  solutions/search/cross-cluster-search.md
Labels: documentation

#2578 Update enable-debug-logging.md
  troubleshoot/ingest/opentelemetry/edot-collector/enable-debug-logging.md
Labels: documentation

#2534 EASE upgrade instructions
  solutions/images/security-ease-cloud-console-edit-project-features.png
  solutions/images/security-ease-cloud-console-manage-project.png
  solutions/security/ai/ease/ease-upgrade.md
  solutions/toc.yml
Labels: documentation

#2593 Update billing.md
  deploy-manage/cloud-organization/billing.md
Labels: documentation, Team:DocsEng

#2623 Fixes Update a document API link
  troubleshoot/elasticsearch/troubleshoot-ingest-pipelines.md
Labels: Team:Admin, SEO

#2597 [Response Ops][9.x & Serverless]: Improve docs for recovered status
  explore-analyze/alerts-cases/alerts/view-alerts.md
  solutions/observability/incident-management/view-alerts.md
Labels: Team:Experience

#2533 Adds Migrate Elasticsearch with minimal downtime page
  manage-data/migrate.md
  manage-data/migrate/migrate-data-between-elasticsearch-clusters-with-minimal-downtime.md
  manage-data/toc.yml
Labels: Team:Ingest

#2631 Adding tags to clarify data management options
  manage-data/lifecycle.md
  manage-data/lifecycle/index-lifecycle-management/manage-lifecycle-integrations-data.md
Labels: documentation

#2536 [Obs AI Assistant] Adds docs for connecting to a local LLM with the Obs AI Assistant
  solutions/images/observability-ai-assistant-lm-studio-load-model-gui.png
  solutions/images/observability-ai-assistant-lms-model-selection.png
  solutions/images/observability-ai-assistant-lms-ps-command.png
  solutions/images/observability-ai-assistant-local-llm-connector-setup.png
  solutions/images/observability-ai-assistant-model-loaded.png
  solutions/observability/connect-to-own-local-llm.md
  solutions/observability/observability-ai-assistant.md
  solutions/toc.yml
Labels: documentation, v9.2.0

#2708 Update differences docs for ech vs serverless
  deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
Labels: documentation

#2712 Corrects use of autorefresh option
  deploy-manage/deploy/self-managed/install-elasticsearch-with-rpm.md
Labels: documentation

#2714 Add link to quickstarts and other edits to Infra get started
  solutions/observability/infra-and-hosts/get-started-with-system-metrics.md
Labels: documentation

#2649 [Security] 9.0.6 release notes
  release-notes/elastic-security/index.md
Labels: release-notes

#2652 [Security] 9.1.3 release notes
  release-notes/elastic-security/index.md
Labels: release-notes

#2646 Update the tutorial "Create a simple dashboard to monitor website logs"
  explore-analyze/dashboards/create-dashboard-of-panels-with-web-server-data.md
Labels: documentation
