Repository elastic/docs-content, pull requests merged in 2025-03, with the labels that each got.

#635 [AutoOps] Add a note to the troubleshooting pages
  deploy-manage/monitor/stack-monitoring/elastic-cloud-stack-monitoring.md
  raw-migrated-files/cloud/cloud/ec-saas-metrics-accessing.md
  troubleshoot/monitoring/cluster-response-time.md
  troubleshoot/monitoring/deployment-health-warnings.md
  troubleshoot/monitoring/high-availability.md
  troubleshoot/monitoring/high-memory-pressure.md
  troubleshoot/monitoring/node-bootlooping.md
  troubleshoot/monitoring/performance.md
  troubleshoot/monitoring/unavailable-nodes.md
  troubleshoot/monitoring/unavailable-shards.md
Labels: documentation

#633 [AutoOps] Update FAQ page
  deploy-manage/monitor/autoops/ec-autoops-faq.md
Labels: documentation

#623 Updates the Watsonx integration page with reranking feature
  solutions/search/inference-api/watsonx-inference-integration.md
Labels: documentation

#698 Update outdated refs to the `prebuilt-jobs.md` file
  solutions/security/advanced-entity-analytics/anomaly-detection.md
  solutions/security/advanced-entity-analytics/behavioral-detection-use-cases.md
  solutions/security/dashboards/entity-analytics-dashboard.md
Labels: documentation

#714 Routing optimization for logsdb is gated by licensing
  manage-data/data-store/data-streams/logs-data-stream.md
Labels: documentation

#719 Updates links pointing to cloud-on-k8s
  deploy-manage/deploy/cloud-on-k8s/configure-eck.md
  deploy-manage/deploy/cloud-on-k8s/elasticsearch-deployment-quickstart.md
  deploy-manage/deploy/cloud-on-k8s/k8s-service-mesh-linkerd.md
  deploy-manage/deploy/cloud-on-k8s/kibana-instance-quickstart.md
  reference/index.md
Labels: documentation

#726 Increase maximum Osquery timeout
  solutions/security/investigate/add-osquery-response-actions.md
  solutions/security/investigate/osquery.md
  solutions/security/investigate/run-osquery-from-alerts.md
  solutions/security/investigate/run-osquery-from-investigation-guides.md
Labels: Team: Security

#739 Removes outdated refs to an Assistant tab in Timeline
  solutions/security/ai/ai-assistant.md
Labels: documentation

#734 Changing links for Plugin management
  deploy-manage/deploy/elastic-cloud/add-plugins-extensions.md
  deploy-manage/tools/snapshot-and-restore/minio-on-premise-repository.md
  deploy-manage/users-roles/cluster-or-deployment-auth/kerberos.md
  explore-analyze/machine-learning/nlp/ml-nlp-inference.md
Labels: documentation

#751 [Inference] Alibaba Cloud Inference Service adds support for deepseek models
  explore-analyze/elastic-inference/inference-api/alibabacloud-ai-search-inference-integration.md
Labels: documentation, enhancement

#746 Updates links pointing to apm-agent-rum-js
  docset.yml
  solutions/observability/apps/apm-agent-central-configuration.md
  solutions/observability/apps/apm-server-binary.md
  solutions/observability/apps/built-in-data-filters.md
  solutions/observability/apps/configure-real-user-monitoring-rum.md
  solutions/observability/apps/filter-application-data.md
  solutions/observability/apps/fleet-managed-apm-server.md
  solutions/observability/apps/metadata.md
  solutions/observability/apps/traces.md
  troubleshoot/observability/apm-agent-rum-js/apm-real-user-monitoring-javascript-agent.md
  troubleshoot/observability/apm/common-problems.md
Labels: documentation, enhancement

#747 Updates links pointing to apm-agent-java
  docset.yml
  raw-migrated-files/docs-content/serverless/observability-apm-get-started.md
  raw-migrated-files/docs-content/serverless/observability-ecs-application-logs.md
  raw-migrated-files/docs-content/serverless/observability-plaintext-application-logs.md
  solutions/observability/apps/api-keys.md
  solutions/observability/apps/apm-agent-central-configuration.md
  solutions/observability/apps/apm-agent-tls-communication.md
  solutions/observability/apps/apm-server-binary.md
  solutions/observability/apps/built-in-data-filters.md
  solutions/observability/apps/elastic-apm-agents.md
  solutions/observability/apps/filter-application-data.md
  solutions/observability/apps/fleet-managed-apm-server.md
  solutions/observability/apps/metadata.md
  solutions/observability/apps/metrics.md
  solutions/observability/apps/monitoring-aws-lambda-functions.md
  solutions/observability/apps/secret-token.md
  solutions/observability/apps/spans.md
  solutions/observability/apps/ssltls-input-settings.md
  solutions/observability/apps/traces.md
  solutions/observability/apps/transaction-sampling.md
  solutions/observability/apps/tutorial-monitor-java-application.md
  solutions/observability/apps/use-opentelemetry-with-apm.md
  solutions/observability/apps/what-happens-when-apm-server-elasticsearch-is-down.md
  solutions/observability/infra-and-hosts/tutorial-observe-kubernetes-deployments.md
  solutions/observability/logs/apm-agent-log-sending.md
  solutions/observability/logs/ecs-formatted-application-logs.md
  solutions/observability/logs/plaintext-application-logs.md
  solutions/observability/logs/stream-application-logs.md
  troubleshoot/observability/apm-agent-java/apm-java-agent.md
  troubleshoot/observability/apm/what-happens-when-apm-server-elasticsearch-is-down.md
Labels: documentation, enhancement

#761 update openshift version
  deploy-manage/deploy/cloud-on-k8s.md
Labels: documentation

#791 Creates CNVM permissions page
  solutions/security/cloud/cloud-native-vulnerability-management.md
  solutions/security/cloud/cnvm-privilege-requirements.md
  solutions/security/cloud/get-started-with-cnvm.md
  solutions/toc.yml
Labels: documentation

#786 [AutoOps] Replace endpoint with connector
  deploy-manage/monitor/autoops/ec-autoops-notifications-settings.md
Labels: documentation

#801 Update link to Elasticsearch reference content
  deploy-manage/deploy/elastic-cloud/edit-stack-settings.md
Labels: documentation

#805 Updates links pointing to ecs
  deploy-manage/monitor/logging-configuration/kibana-log-settings-examples.md
  deploy-manage/monitor/logging-configuration/kibana-logging.md
  deploy-manage/production-guidance.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-categories.md
  explore-analyze/transforms/transform-checkpoints.md
  manage-data/ingest/ingesting-data-from-applications/ingest-logs-from-python-application-using-filebeat.md
  manage-data/ingest/transform-enrich/ingest-pipelines-serverless.md
  manage-data/ingest/transform-enrich/ingest-pipelines.md
  raw-migrated-files/docs-content/serverless/observability-plaintext-application-logs.md
  reference/ecs.md
  reference/ingestion-tools/fleet/kafka-output-settings.md
  reference/observability/fields-and-object-schemas.md
  reference/observability/fields-and-object-schemas/logs-app-fields.md
  reference/observability/fields-and-object-schemas/metrics-app-fields.md
  reference/observability/serverless/infrastructure-app-fields.md
  reference/security/fields-and-object-schemas/alert-schema.md
  reference/security/fields-and-object-schemas/siem-field-reference.md
  reference/security/fields-and-object-schemas/timeline-object-schema.md
  solutions/observability/apps/find-transaction-latency-failure-correlations.md
  solutions/observability/apps/tutorial-monitor-java-application.md
  solutions/observability/logs/configure-data-sources.md
  solutions/observability/logs/inspect-log-anomalies.md
  solutions/observability/logs/parse-route-logs.md
  solutions/observability/logs/plaintext-application-logs.md
  solutions/security/dashboards/data-quality-dashboard.md
  solutions/security/detect-and-alert/create-manage-value-lists.md
  solutions/security/detect-and-alert/view-detection-alert-details.md
  solutions/security/explore/configure-network-map-data.md
  solutions/security/get-started/automatic-import.md
  solutions/security/get-started/enable-threat-intelligence-integrations.md
  solutions/security/get-started/ingest-data-to-elastic-security.md
  troubleshoot/kibana/using-kibana-server-logs.md
Labels: documentation, enhancement

#789 Cleans the "Detections and alerts" page
  raw-migrated-files/docs-content/serverless/security-detection-engine-overview.md
  raw-migrated-files/toc.yml
  solutions/security/configure-elastic-defend/configure-an-integration-policy-for-elastic-defend.md
  solutions/security/detect-and-alert.md
Labels: documentation, Team: Security

#850 Fix broken ml job links and remove duplicate prebuilt jobs page
  redirects.yml
  reference/data-analysis/machine-learning/ootb-ml-jobs-siem.md
  reference/security/images/link.svg
  reference/security/prebuilt-anomaly-detection-jobs.md
  reference/toc.yml
  solutions/security/advanced-entity-analytics/anomaly-detection.md
  solutions/security/advanced-entity-analytics/behavioral-detection-use-cases.md
  solutions/security/dashboards/entity-analytics-dashboard.md
Labels: Team: Security

#836 Adds Endpoint Insights sub-feature privilege
  solutions/security/configure-elastic-defend/elastic-defend-feature-privileges.md
Labels: Team: Security

#881 ECE Networking Port Requirements Update
  deploy-manage/deploy/cloud-enterprise/ece-networking-prereq.md
Labels: documentation

#849 Update ccs compatibility matrix with 9.0
  solutions/search/cross-cluster-search.md
Labels: documentation

#893 [9.0 & Serverless] Editing, exporting, and importing prebuilt rules
  solutions/security/detect-and-alert/manage-detection-rules.md
Labels: documentation

#908 Clarify ECK support scope for ingress controllers
  deploy-manage/deploy/cloud-on-k8s/elastic-maps-server.md
  deploy-manage/deploy/cloud-on-k8s/http-configuration.md
  deploy-manage/deploy/cloud-on-k8s/managing-deployments-using-helm-chart.md
  deploy-manage/deploy/cloud-on-k8s/recipes.md
  deploy-manage/deploy/cloud-on-k8s/requests-routing-to-elasticsearch-nodes.md
Labels: documentation

#904 [9.0 & Serverless] Updating customized prebuilt rules
  solutions/images/security-prebuilt-rules-update-advanced.png
  solutions/images/security-prebuilt-rules-update-diff-advanced.png
  solutions/images/security-prebuilt-rules-update-diff-basic.png
  solutions/images/security-prebuilt-rules-update-diff.png
  solutions/security/detect-and-alert/install-manage-elastic-prebuilt-rules.md
  solutions/security/detect-and-alert/manage-detection-rules.md
  solutions/security/detect-and-alert/prebuilt-rules-update-modified-unmodified.md
  solutions/toc.yml
Labels: documentation

#825 [security][8.18/9.0] Automatic import updates
  solutions/security/get-started/automatic-import.md
Labels: documentation, enhancement

#942 Updates risk scoring requirements
  solutions/security/advanced-entity-analytics/entity-risk-scoring-requirements.md
Labels: Team: Security

#964 Expand guidance on testing an upgrade
  deploy-manage/upgrade/prepare-to-upgrade.md
Labels: documentation

#892 [9.0 & Serverless] Rule gaps and manual rule runs
  solutions/images/security-gaps-table.png
  solutions/images/security-manual-rule-run-table.png
  solutions/images/security-monitor-table.png
  solutions/security/detect-and-alert/manage-detection-rules.md
  solutions/security/detect-and-alert/monitor-rule-executions.md
Labels: documentation

#978 Fix symbol being used on mapped_pages front matter
  reference/index.md
Labels: bug
