Repository elastic/docs-content, pull requests merged in 2025-06, with the labels that each got.

#1577 Add rescorer retriever to the retrievers overview
  solutions/search/retrievers-overview.md
Labels: documentation

#1452 [Security] 9.0.2 release notes
  release-notes/elastic-security/index.md
Labels: Team:Security, release-notes, v9.0.2

#1576 clarify MFA for team use case
  cloud-account/multifactor-authentication.md
Labels: documentation, supportability

#1600 docs: fix typo in reading-and-writing-documents.md
  deploy-manage/distributed-architecture/reading-and-writing-documents.md
Labels: Team:Admin

#1588 Adds Endpoint Exceptions privilege to serverless
  solutions/security/configure-elastic-defend/elastic-defend-feature-privileges.md
Labels: Team:Experience

#1625 Relax snapshot repo backup docs
  deploy-manage/tools/snapshot-and-restore/elastic-cloud-hosted.md
  deploy-manage/tools/snapshot-and-restore/self-managed.md
Labels: Team:Admin

#1629 Fix typo at eck-stack-monitoring.md
  deploy-manage/monitor/stack-monitoring/eck-stack-monitoring.md
Labels: Team:Admin

#1540 [Serverless][Security]: Edit highlighted fields in alert flyout
  solutions/security/detect-and-alert/view-detection-alert-details.md
Labels: Serverless, Team:Security

#1582 [REQUEST][Serverless]: Enable endpoint actions in events
  solutions/security/endpoint-response-actions.md
  solutions/security/endpoint-response-actions/isolate-host.md
Labels: documentation, Serverless

#1697 Add refresh_interval and analyzer request examples from old API ref
  deploy-manage/production-guidance/optimize-performance/indexing-speed.md
  manage-data/data-store/text-analysis/specify-an-analyzer.md
Labels: API docs

#1706 Task backlog | Long running search
  troubleshoot/elasticsearch/task-queue-backlog.md
Labels: bug

#1651 Update rare script job in prebuilt ML jobs document
  reference/data-analysis/machine-learning/ootb-ml-jobs-siem.md
Labels: documentation, v8.19.0, v9.1.0

#1715 Doc: Remove note about agent certificate for control plane traffic
  reference/fleet/fleet-agent-proxy-managed.md
Labels: documentation

#1628 Restructure Search UI landing page
  deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
  solutions/search/site-or-app/search-ui.md
Labels: documentation

#1735 [Security][9.x & Serverless] Don't modify index mappings for Alerts indices
  reference/security/fields-and-object-schemas/alert-schema.md
  solutions/security/detect-and-alert/about-detection-rules.md
  solutions/security/detect-and-alert/query-alert-indices.md
Labels: documentation, Team:Security

#1507 ECE allocators capacity updated for svc restart
  deploy-manage/deploy/cloud-enterprise/ece-manage-capacity.md
  deploy-manage/toc.yml
Labels: ece, Team:Admin

#1730 Adds Update mapping API examples page
  manage-data/data-store/mapping/update-mappings-examples.md
  manage-data/toc.yml
Labels: documentation, Team:Developer

#1418 Update ece-manage-capacity for Podman limitation
  deploy-manage/deploy/cloud-enterprise/ece-manage-capacity.md
Labels: ece, Team:Admin

#1756 Adds the Serverless changelog for June 16, 2025
  release-notes/elastic-cloud-serverless/index.md
Labels: Serverless, Team:Admin

#1771 Add links to mOTLP doc
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
  solutions/observability/get-started/quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md
Labels: enhancement

#1768 Adds ack_watch example to the Watcher - Actions page
  explore-analyze/alerts-cases/watcher/actions.md
Labels: documentation, Team:Developer

#1780 Adds the "Execute a watch" API example page
  explore-analyze/alerts-cases/watcher/execute-watch.md
  explore-analyze/toc.yml
Labels: documentation, Team:Developer

#1778 [Security] Adds section about Elastic Managed LLM to Security AI assistant
  solutions/security/ai/ai-assistant.md
Labels: documentation, ml, nlp, v9.1.0

#1816 Fix unused tags not rendering
  reference/fleet/agent-command-reference.md
Labels: bug

#1813 Clarify prerequisites, limitations, and troubleshooting in agent quickstart
  solutions/observability/get-started/quickstart-monitor-hosts-with-elastic-agent.md
Labels: Team:Ingest

#1809 Update agent-command-reference.md
  reference/fleet/agent-command-reference.md
Labels: bug

#1445 Elastic Defend advanced settings
  reference/security/defend-advanced-settings.md
  reference/security/toc.yml
  solutions/security/configure-elastic-defend/configure-an-integration-policy-for-elastic-defend.md
Labels: Team:Experience

#1726 (new page) Logstash Diag
  troubleshoot/ingest/logstash/diagnostic.md
  troubleshoot/toc.yml
Labels: enhancement

#1898 Adds KB settings known issue to Security known issues
  release-notes/elastic-security/known-issues.md
Labels: known-issue

#1647 ECH/ECK remote clusters doc is incorrect for trust.yml
  deploy-manage/remote-clusters/ec-enable-ccs-for-eck.md
Labels: bug, Team:Admin

#1938 Remove mentions of in preview
  deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
Labels: documentation, Team:Admin

#1927 Add note about direct IO on vector rescoring
  deploy-manage/production-guidance/optimize-performance/approximate-knn-search.md
Labels: v9.1.0

#1951 Removes applies_to tag for Serverless on Watcher page
  explore-analyze/alerts-cases/watcher/enable-watcher.md
Labels: documentation, Team:Admin

#1957 [Security][9.x & Serverless] Don't modify index mappings for Alerts indices pt.2
  reference/security/fields-and-object-schemas/alert-schema.md
  solutions/security/detect-and-alert/about-detection-rules.md
  solutions/security/detect-and-alert/query-alert-indices.md
Labels: Team:Security, Team:Experience
