Repository elastic/docs-content, pull requests merged in 2025-05, with the labels that each got.

#1362 Docs update 8.17.6/8.18.1/9.0.1 Stack Releases
  deploy-manage/deploy/cloud-enterprise/ece-install-offline-images.md
  deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md
Labels: documentation

#1349 [9.0/Serverless] Updated outdated images of Timeline
  solutions/images/security-correlation-tab-eql-query.png
  solutions/images/security-esql-tab.png
  solutions/images/security-ig-timeline-query.png
  solutions/images/security-ig-timeline.png
  solutions/images/security-timeline-sidebar.png
  solutions/images/security-timeline-ui-renderer.png
  solutions/images/security-timeline-ui-updated.png
Labels: Team:Security

#1374 Update mapping.md
  manage-data/data-store/mapping.md
Labels: v8.19.0, v9.1.0

#1382 Removes Serverless changelog from index
  serverless/index.asciidoc
Labels: bug

#1320 [Reference] Revisit Observability landing page
  reference/observability/index.md
Labels: documentation, enhancement

#1304 [Reference] Revisit Security landing page
  reference/security/index.md
Labels: documentation, Team:Security

#1246 Clarify replica shard allocation step in rolling restart procedure
  deploy-manage/maintenance/start-stop-services/full-cluster-restart-rolling-restart-procedures.md
Labels: documentation

#1354 [Reference] Revisit the ingestion tools landing page
  reference/ingestion-tools/index.md
Labels: documentation

#1355 [Reference] Revisit the data analysis landing page
  reference/data-analysis/index.md
Labels: documentation

#1394 Correct ECE doc KB reference
  deploy-manage/upgrade/orchestrator/upgrade-cloud-enterprise.md
Labels: documentation, supportability, ece

#1398 Extend CCS matrix with 8.x minor versions
  solutions/search/cross-cluster-search.md
Labels: documentation

#1412 Modify links and add repo to docset
  docset.yml
  manage-data/ingest/ingesting-timeseries-data.md
  reference/fleet/otel-agent.md
  solutions/observability/apm/collect-application-data.md
  solutions/observability/apm/use-opentelemetry-with-apm.md
  solutions/observability/applications/llm-observability.md
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
  solutions/observability/get-started/quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md
Labels: documentation

#1439 Adds the Serverless changelog for May 19, 2025
  release-notes/elastic-cloud-serverless/index.md
Labels: Serverless

#1379 Update automatic-migration.md
  solutions/security/get-started/automatic-migration.md
Labels: documentation

#1441 Edit Fleet and APM docs for OTel references
  reference/fleet/agent-command-reference.md
  reference/fleet/otel-agent-transform.md
  reference/fleet/otel-agent.md
  solutions/observability/apm/attributes.md
  solutions/observability/apm/upstream-opentelemetry-collectors-language-sdks.md
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
Labels: documentation

#1446 Docs for Fleet advanced config in ECK
  deploy-manage/deploy/cloud-on-k8s/configuration-fleet.md
  reference/fleet/advanced-kubernetes-managed-by-fleet.md
Labels: Team:Admin

#1459 Update minimum stack version to 8.0.0 for ECE 4
  deploy-manage/upgrade/orchestrator/upgrade-cloud-enterprise.md
Labels: Team:Admin

#1457 Debian pkg config file updated in snippet
  deploy-manage/deploy/self-managed/_snippets/etc-elasticsearch.md
  deploy-manage/deploy/self-managed/install-elasticsearch-with-debian-package.md
  deploy-manage/deploy/self-managed/install-elasticsearch-with-rpm.md
Labels: Team:Admin

#1488 Add tech preview note
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
Labels: documentation

#1485 Make ESQL Full Text Functions GA
  solutions/search/esql-for-search.md
Labels: documentation, Team:Search

#1513 Revert "Update `recore_vector` preview/GA status in knn.md"
  solutions/search/vector/knn.md
Labels: v9.1.0

#1421 Clarifications on 'no downtime' during upgrades
  deploy-manage/upgrade/deployment-or-cluster/upgrade-on-ech.md
Labels: Team:Admin

#1531 Remove the Serverless label from ILM docs
  manage-data/lifecycle/curator.md
  manage-data/lifecycle/data-tiers.md
  manage-data/lifecycle/index-lifecycle-management/configure-lifecycle-policy.md
  manage-data/lifecycle/index-lifecycle-management/index-lifecycle.md
  manage-data/lifecycle/index-lifecycle-management/index-management-in-kibana.md
  manage-data/lifecycle/index-lifecycle-management/manage-existing-indices.md
  manage-data/lifecycle/index-lifecycle-management/migrate-index-allocation-filters-to-node-roles.md
  manage-data/lifecycle/index-lifecycle-management/migrate-index-management.md
  manage-data/lifecycle/index-lifecycle-management/policy-updates.md
  manage-data/lifecycle/index-lifecycle-management/restore-managed-data-stream-index.md
  manage-data/lifecycle/index-lifecycle-management/rollover.md
  manage-data/lifecycle/index-lifecycle-management/skip-rollover.md
  manage-data/lifecycle/index-lifecycle-management/start-stop-index-lifecycle-management.md
  manage-data/lifecycle/index-lifecycle-management/tutorial-automate-rollover.md
  manage-data/lifecycle/index-lifecycle-management/tutorial-customize-built-in-policies.md
Labels: Team:Admin
