Repository elastic/docs-content, pull requests merged in 2025-09, with the labels that each got.

#2773 [SEARCH] Improves kkn docs based on SEO guidelines
  solutions/search/vector/knn.md
Labels: documentation, Team:Developer, v9.0.2

#2781 [SEARCH] Improves bring your own vectors page based on SEO guidelines
  solutions/search/vector/bring-own-vectors.md
Labels: documentation, Team:Developer, v9.2.0

#2794 Replaces all links to point to the deduplicated/reconciled roles page
  deploy-manage/manage-spaces.md
  deploy-manage/monitor/stack-monitoring/es-self-monitoring-prod.md
  deploy-manage/users-roles.md
  deploy-manage/users-roles/_snippets/org-vs-deploy-sso.md
  deploy-manage/users-roles/cloud-organization/user-roles.md
  deploy-manage/users-roles/cluster-or-deployment-auth.md
  deploy-manage/users-roles/cluster-or-deployment-auth/built-in-roles.md
  deploy-manage/users-roles/cluster-or-deployment-auth/built-in-users.md
  deploy-manage/users-roles/cluster-or-deployment-auth/mapping-users-groups-to-roles.md
  deploy-manage/users-roles/cluster-or-deployment-auth/user-roles.md
  explore-analyze/discover/save-open-search.md
  explore-analyze/query-filter/tools/saved-queries.md
  explore-analyze/transforms/transform-setup.md
  explore-analyze/visualize/canvas.md
  explore-analyze/visualize/graph/graph-configuration.md
  explore-analyze/visualize/maps/maps-getting-started.md
  manage-data/ingest/transform-enrich/set-up-an-enrich-processor.md
  solutions/observability/apm/create-assign-feature-roles-to-apm-server-users.md
  solutions/observability/apm/monitor-fleet-managed-apm-server.md
  solutions/observability/apm/secure-access-to-applications-ui.md
  solutions/observability/apm/use-metricbeat-to-send-monitoring-data.md
  solutions/observability/data-set-quality-monitoring.md
  solutions/observability/get-started/quickstart-collect-data-with-aws-firehose.md
  solutions/observability/get-started/quickstart-monitor-hosts-with-elastic-agent.md
  solutions/observability/get-started/quickstart-monitor-kubernetes-cluster-with-elastic-agent.md
  solutions/observability/incident-management/configure-service-level-objective-slo-access.md
  solutions/observability/synthetics/grant-access-to-secured-resources.md
  solutions/observability/synthetics/reader-role.md
  solutions/observability/synthetics/setup-role.md
  solutions/observability/synthetics/writer-role.md
  solutions/search/query-rules-ui.md
  solutions/security/detect-and-alert/create-detection-rule.md
Labels: documentation

#2793 [SEARCH] Improves sparse vector and vector search tutorial pages based on SEO guidelines
  solutions/search/vector/dense-versus-sparse-ingest-pipelines.md
  solutions/search/vector/sparse-vector.md
Labels: documentation, Team:Developer, v9.2.0

#2806 [ML] Adds recommendation about using time functions
  reference/data-analysis/machine-learning/ml-time-functions.md
Labels: documentation, Team:Developer, v9.2.0, v9.0.3, v9.1.3

#2803 Small doc improvement about MFA
  cloud-account/multifactor-authentication.md
Labels: documentation, supportability, Team:Admin

#2766 Clarify ECK license update doc
  deploy-manage/license/manage-your-license-in-eck.md
Labels: documentation, supportability, Team:Platform

#2855 [ResponseOps][Docs]: Maintenance window GAing and category options removed
  explore-analyze/alerts-cases/alerts/maintenance-windows.md
  explore-analyze/images/kibana-create-maintenance-window-filter.png
  explore-analyze/images/kibana-create-maintenance-window.png
Labels: Team:Experience

#2915 [Security] 9.0.7 release notes
  release-notes/elastic-security/breaking-changes.md
  release-notes/elastic-security/index.md
Labels: release-notes

#2734 Adds recommendation about choosing project profile
  solutions/search/vector/bring-own-vectors.md
  solutions/search/vector/dense-vector.md
  solutions/search/vector/knn.md
Labels: documentation, Serverless, Team:Developer

#2917 [Security] 9.1.4 release notes
  release-notes/elastic-security/index.md
Labels: release-notes

#2812 [Obs AI Assistant] Add LLM performance matrix docs
  solutions/observability/connect-to-own-local-llm.md
  solutions/observability/llm-performance-matrix.md
  solutions/observability/observability-ai-assistant.md
  solutions/toc.yml
Labels: documentation, v9.2.0

#3036 Update diagnose-unassigned-shards.md
  troubleshoot/elasticsearch/diagnose-unassigned-shards.md
Labels: enhancement, supportability

#3041 Modifies H1 title for better SEO
  reference/observability/index.md
Labels: enhancement

#3069 Fix kube stack docs automation
  .github/workflows/update-kube-stack-version.yml
  scripts/update_kube_stack_version.py
Labels: bug

#2365 minor defend advanced option clarifications
  reference/security/defend-advanced-settings.md
Labels: Team:Security

#2754 Clarify adminconsole certs
  deploy-manage/security/secure-your-elastic-cloud-enterprise-installation/manage-security-certificates.md
Labels: documentation, supportability, Team:Platform

#3066 Clarify ECE - document host maintenance with podman
  deploy-manage/maintenance/ece/perform-ece-hosts-maintenance.md
Labels: documentation, supportability, Team:Admin

#2795 Add new Elastic intro section
  deploy-manage/deploy/self-managed.md
  docset.yml
  extend/index.md
  get-started/deployment-options.md
  get-started/howto-use-the-docs.md
  get-started/images/elastic-platform.png
  get-started/index.md
  get-started/the-stack.md
  get-started/toc.yml
  versions.md
Labels: documentation

#3186 Update obs-serverless-project.md
  solutions/_snippets/obs-serverless-project.md
Labels: enhancement

#3161 Update ECE - "Manage Elastic Stack versions" page
  deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md
Labels: documentation, supportability, Team:Admin

#2489 Expand filebased user for recovering security
  deploy-manage/users-roles/cluster-or-deployment-auth/file-based.md
  troubleshoot/elasticsearch.md
  troubleshoot/elasticsearch/file-based-recovery.md
  troubleshoot/toc.yml
Labels: enhancement

#2854 Update create-detection-rule.md
  solutions/security/detect-and-alert/create-detection-rule.md
Labels: documentation, Team:Experience

#3212 Remove old requirement
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
Labels: documentation

#3004 Update versioning and availability
  get-started/howto-use-the-docs.md
  get-started/versioning-availability.md
  versions.md
Labels: wip
