Repository elastic/docs-content, pull requests merged in 2025-02, with the labels that each got.

#290 [E&A] Refine ML intro
  explore-analyze/machine-learning.md
  raw-migrated-files/docs-content/serverless/machine-learning.md
  raw-migrated-files/stack-docs/machine-learning/machine-learning-intro.md
  raw-migrated-files/toc.yml
Labels: ml

#288 Fix formatting of dropdown titles
  solutions/security/configure-elastic-defend/configure-offline-endpoints-air-gapped-environments.md
Labels: Team: Security

#304 [E&A] Refines anomaly detection docs set part 1.
  explore-analyze/machine-learning.md
  explore-analyze/machine-learning/anomaly-detection.md
  explore-analyze/machine-learning/anomaly-detection/anomaly-detection-scale.md
  explore-analyze/machine-learning/anomaly-detection/anomaly-how-tos.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-algorithms.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-concepts.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-explain.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-finding-anomalies.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-forecast.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-plan.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-view-results.md
  explore-analyze/machine-learning/anomaly-detection/ml-anomaly-detection-job-types.md
  explore-analyze/machine-learning/anomaly-detection/ml-api-quickref.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-aggregation.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-alerts.md
  explore-analyze/machine-learning/anomaly-detection/ml-delayed-data-detection.md
  explore-analyze/machine-learning/anomaly-detection/ml-getting-started.md
  explore-analyze/machine-learning/machine-learning-in-kibana.md
  explore-analyze/machine-learning/machine-learning-in-kibana/xpack-ml-aiops.md
  explore-analyze/machine-learning/machine-learning-in-kibana/xpack-ml-anomalies.md
  explore-analyze/machine-learning/machine-learning-in-kibana/xpack-ml-dfanalytics.md
  explore-analyze/machine-learning/setting-up-machine-learning.md
  raw-migrated-files/kibana/kibana/xpack-ml-anomalies.md
  raw-migrated-files/stack-docs/machine-learning/ml-ad-overview.md
  raw-migrated-files/toc.yml
Labels: ml

#308 [E&A] Refine anomaly detection docs set part 2.
  explore-analyze/machine-learning/anomaly-detection/geographic-anomalies.md
  explore-analyze/machine-learning/anomaly-detection/mapping-anomalies.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-resources.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-troubleshooting.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-categories.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-detector-custom-rules.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-transform.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-url.md
  explore-analyze/machine-learning/anomaly-detection/ml-jobs-from-lens.md
  explore-analyze/machine-learning/anomaly-detection/ml-limitations.md
  explore-analyze/machine-learning/anomaly-detection/ml-reverting-model-snapshot.md
  explore-analyze/machine-learning/anomaly-detection/move-jobs.md
  explore-analyze/machine-learning/anomaly-detection/ootb-ml-jobs.md
  explore-analyze/toc.yml
Labels: ml

#323 [E&A] Refines outlier detection, classification, and regression pages
  docset.yml
  explore-analyze/machine-learning/data-frame-analytics.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-classification.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-finding-outliers.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-overview.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-regression.md
  raw-migrated-files/kibana/kibana/xpack-ml-dfanalytics.md
  raw-migrated-files/stack-docs/machine-learning/index.md
  raw-migrated-files/stack-docs/machine-learning/ml-dfanalytics.md
  raw-migrated-files/toc.yml
Labels: ml

#327 [E&A] Refined data frame analytics advanced concepts and other pages
  explore-analyze/machine-learning/data-frame-analytics/dfa-regression-lossfunction.md
  explore-analyze/machine-learning/data-frame-analytics/hyperparameters.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-concepts.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-custom-urls.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-limitations.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-phases.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-resources.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-scale.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfanalytics-apis.md
  explore-analyze/machine-learning/data-frame-analytics/ml-feature-encoding.md
  explore-analyze/machine-learning/data-frame-analytics/ml-feature-importance.md
  explore-analyze/machine-learning/data-frame-analytics/ml-feature-processors.md
  explore-analyze/machine-learning/data-frame-analytics/ml-trained-models.md
Labels: ml

#301 Adds 'Backup, high availability, and resilience tools' landing page
  deploy-manage/tools.md
Labels: documentation

#330 [E&A] Refines NLP model conceptual docs
  explore-analyze/machine-learning/nlp.md
  explore-analyze/machine-learning/nlp/ml-nlp-built-in-models.md
  explore-analyze/machine-learning/nlp/ml-nlp-e5.md
  explore-analyze/machine-learning/nlp/ml-nlp-elser.md
  explore-analyze/machine-learning/nlp/ml-nlp-model-ref.md
  explore-analyze/machine-learning/nlp/ml-nlp-rerank.md
  explore-analyze/machine-learning/nlp/nlp-example.md
Labels: ml, nlp

#348 [E&A] Deletes AIOps Labs section
  explore-analyze/machine-learning/aiops-labs.md
  explore-analyze/machine-learning/aiops-labs/observability-aiops-analyze-spikes.md
  explore-analyze/machine-learning/aiops-labs/observability-aiops-detect-anomalies.md
  explore-analyze/machine-learning/aiops-labs/observability-aiops-detect-change-points.md
  explore-analyze/machine-learning/aiops-labs/observability-aiops-forecast-anomalies.md
  explore-analyze/machine-learning/aiops-labs/observability-aiops-tune-anomaly-detection-job.md
  explore-analyze/toc.yml
  raw-migrated-files/docs-content/serverless/observability-log-monitoring.md
  raw-migrated-files/docs-content/serverless/observability-machine-learning.md
  raw-migrated-files/docs-content/serverless/observability-quickstarts-monitor-hosts-with-elastic-agent.md
  raw-migrated-files/docs-content/serverless/observability-serverless-observability-overview.md
  raw-migrated-files/docs-content/serverless/observability-triage-threshold-breaches.md
  raw-migrated-files/docs-content/serverless/quickstart-monitor-hosts-with-otel.md
  raw-migrated-files/docs-content/serverless/what-is-observability-serverless.md
  raw-migrated-files/kibana/kibana/xpack-ml-aiops.md
  raw-migrated-files/observability-docs/observability/quickstart-monitor-hosts-with-elastic-agent.md
  raw-migrated-files/observability-docs/observability/quickstart-monitor-hosts-with-otel.md
  raw-migrated-files/observability-docs/observability/triage-threshold-breaches.md
  raw-migrated-files/toc.yml
  solutions/observability/incident-management/create-an-anomaly-detection-rule.md
Labels: ml

#351 [E&A] Refines transforms section
  explore-analyze/transforms.md
  explore-analyze/transforms/ecommerce-transforms.md
  explore-analyze/transforms/transform-alerts.md
  explore-analyze/transforms/transform-api-quickref.md
  explore-analyze/transforms/transform-checkpoints.md
  explore-analyze/transforms/transform-examples.md
  explore-analyze/transforms/transform-limitations.md
  explore-analyze/transforms/transform-overview.md
  explore-analyze/transforms/transform-painless-examples.md
  explore-analyze/transforms/transform-scale.md
  explore-analyze/transforms/transform-setup.md
  explore-analyze/transforms/transform-usage.md
  raw-migrated-files/docs-content/serverless/transforms.md
  raw-migrated-files/elasticsearch/elasticsearch-reference/data-rollup-transform.md
  raw-migrated-files/elasticsearch/elasticsearch-reference/transforms.md
  raw-migrated-files/toc.yml
Labels: ml, nlp

#350 [Docs] Update Inference endpoints UI
  images/kibana-inference-endpoints-ui.png
  raw-migrated-files/kibana/kibana/inference-endpoints.md
Labels: documentation

#396 Add navigation_title to inference pages
  solutions/search/inference-api/alibabacloud-ai-search-inference-integration.md
  solutions/search/inference-api/amazon-bedrock-inference-integration.md
  solutions/search/inference-api/anthropic-inference-integration.md
  solutions/search/inference-api/azure-ai-studio-inference-integration.md
  solutions/search/inference-api/azure-openai-inference-integration.md
  solutions/search/inference-api/chat-completion-inference-api.md
  solutions/search/inference-api/cohere-inference-integration.md
  solutions/search/inference-api/elastic-inference-service-eis.md
  solutions/search/inference-api/elasticsearch-inference-integration.md
  solutions/search/inference-api/elser-inference-integration.md
  solutions/search/inference-api/google-ai-studio-inference-integration.md
  solutions/search/inference-api/google-vertex-ai-inference-integration.md
  solutions/search/inference-api/huggingface-inference-integration.md
  solutions/search/inference-api/jinaai-inference-integration.md
  solutions/search/inference-api/mistral-inference-integration.md
  solutions/search/inference-api/openai-inference-integration.md
  solutions/search/inference-api/watsonx-inference-integration.md
Labels: documentation

#395 [E&A] Refines Watcher
  deploy-manage/deploy/elastic-cloud/restrictions-known-problems.md
  explore-analyze/alerts-cases/watcher.md
  explore-analyze/alerts-cases/watcher/action-conditions.md
  explore-analyze/alerts-cases/watcher/action-foreach.md
  explore-analyze/alerts-cases/watcher/actions-email.md
  explore-analyze/alerts-cases/watcher/actions-index.md
  explore-analyze/alerts-cases/watcher/actions-jira.md
  explore-analyze/alerts-cases/watcher/actions-logging.md
  explore-analyze/alerts-cases/watcher/actions-pagerduty.md
  explore-analyze/alerts-cases/watcher/actions-slack.md
  explore-analyze/alerts-cases/watcher/actions-webhook.md
  explore-analyze/alerts-cases/watcher/actions.md
  explore-analyze/alerts-cases/watcher/condition-always.md
  explore-analyze/alerts-cases/watcher/condition-array-compare.md
  explore-analyze/alerts-cases/watcher/condition-compare.md
  explore-analyze/alerts-cases/watcher/condition-never.md
  explore-analyze/alerts-cases/watcher/condition-script.md
  explore-analyze/alerts-cases/watcher/condition.md
  explore-analyze/alerts-cases/watcher/enable-watcher.md
  explore-analyze/alerts-cases/watcher/encrypting-data.md
  explore-analyze/alerts-cases/watcher/example-watches.md
  explore-analyze/alerts-cases/watcher/input-chain.md
  explore-analyze/alerts-cases/watcher/input-http.md
  explore-analyze/alerts-cases/watcher/input-search.md
  explore-analyze/alerts-cases/watcher/input-simple.md
  explore-analyze/alerts-cases/watcher/input.md
  explore-analyze/alerts-cases/watcher/managing-watches.md
  explore-analyze/alerts-cases/watcher/transform-chain.md
  explore-analyze/alerts-cases/watcher/transform-script.md
  explore-analyze/alerts-cases/watcher/transform-search.md
  explore-analyze/alerts-cases/watcher/transform.md
  explore-analyze/alerts-cases/watcher/trigger-schedule.md
  explore-analyze/alerts-cases/watcher/trigger.md
  explore-analyze/alerts-cases/watcher/watch-cluster-status.md
  explore-analyze/alerts-cases/watcher/watcher-getting-started.md
  explore-analyze/alerts-cases/watcher/watcher-limitations.md
  explore-analyze/alerts-cases/watcher/watcher-ui.md
  explore-analyze/scripting/painless-lab.md
  explore-analyze/toc.yml
  raw-migrated-files/elasticsearch/elasticsearch-reference/xpack-alerting.md
  raw-migrated-files/toc.yml
Labels: documentation

#375 Adds 'Snapshot and restore' overview page
  deploy-manage/tools/snapshot-and-restore.md
Labels: documentation

#413 [E&A] Refines aggregations
  explore-analyze/aggregations.md
  explore-analyze/aggregations/tutorial-analyze-ecommerce-data-with-aggregations-using-query-dsl.md
Labels: documentation

#440 Add missing callouts
  solutions/search/inference-api/chat-completion-inference-api.md
  solutions/search/inference-api/jinaai-inference-integration.md
Labels: documentation

#412 [GS] Edits get started section
  get-started/contribute.md
  get-started/installing-elastic-stack.md
  get-started/introduction.md
  get-started/stack-components.md
  get-started/the-stack.md
  get-started/toc.yml
  get-started/use-cases.md
Labels: documentation

#422 Adds Manage snapshot repositories page
  deploy-manage/tools/snapshot-and-restore.md
  deploy-manage/tools/snapshot-and-restore/manage-snapshot-repositories.md
Labels: documentation

#421 [D&M] Drafts maintenance content
  deploy-manage/maintenance.md
  deploy-manage/maintenance/add-and-remove-elasticsearch-nodes.md
  deploy-manage/maintenance/ece.md
  deploy-manage/maintenance/ece/delete-ece-hosts.md
  deploy-manage/maintenance/ece/deployments-maintenance.md
  deploy-manage/maintenance/ece/enable-maintenance-mode.md
  deploy-manage/maintenance/ece/maintenance-activities.md
  deploy-manage/maintenance/ece/move-nodes-instances-from-allocators.md
  deploy-manage/maintenance/ece/pause-instance.md
  deploy-manage/maintenance/ece/perform-ece-hosts-maintenance.md
  deploy-manage/maintenance/ece/scale-out-installation.md
  deploy-manage/maintenance/ece/start-stop-routing-requests.md
  deploy-manage/maintenance/start-stop-services.md
  deploy-manage/maintenance/start-stop-services/full-cluster-restart-rolling-restart-procedures.md
  deploy-manage/maintenance/start-stop-services/restart-an-ece-deployment.md
  deploy-manage/maintenance/start-stop-services/restart-cloud-hosted-deployment.md
  deploy-manage/maintenance/start-stop-services/start-stop-elasticsearch.md
  deploy-manage/maintenance/start-stop-services/start-stop-kibana.md
  raw-migrated-files/cloud/cloud-enterprise/ece-maintenance-mode-routing.md
  raw-migrated-files/cloud/cloud/ec-api-deployment-other.md
  raw-migrated-files/cloud/cloud/ec-restart-deployment.md
  raw-migrated-files/elasticsearch/elasticsearch-reference/security-basic-setup.md
  raw-migrated-files/elasticsearch/elasticsearch-reference/starting-elasticsearch.md
  raw-migrated-files/elasticsearch/elasticsearch-reference/stopping-elasticsearch.md
  raw-migrated-files/stack-docs/elastic-stack/installing-stack-demo-self.md
  raw-migrated-files/toc.yml
Labels: documentation

#574 [AutoOps] Add Email connector
  deploy-manage/monitor/autoops/ec-autoops-notifications-settings.md
Labels: documentation

#497 [Docs migration] Cleans up getting started files - Pt. 1
  images/security-dataview-filter-example copy.gif
  images/serverless--getting-started-dataview-button-highlighted.png
  images/serverless--getting-started-dataview-filter-example.gif
  raw-migrated-files/docs-content/serverless/security-advanced-settings.md
  raw-migrated-files/docs-content/serverless/security-data-views-in-sec.md
  raw-migrated-files/docs-content/serverless/security-ingest-data.md
  raw-migrated-files/toc.yml
  solutions/security/get-started/configure-advanced-settings.md
  solutions/security/get-started/data-views-elastic-security.md
  solutions/security/get-started/ingest-data-to-elastic-security.md
Labels: documentation
