Repository elastic/docs-content, pull requests merged in 2025-04, with the labels that each got.

#982 Upgrade notes for logsdb mode
  manage-data/data-store/data-streams/logs-data-stream.md
Labels: documentation

#992 Fix notes header for logsdb upgrading
  manage-data/data-store/data-streams/logs-data-stream.md
Labels: documentation

#890 [9.0 & Serverless] Logged ES queries now provided for new terms, machine learning, custom query, threshold rule types
  solutions/security/detect-and-alert/create-detection-rule.md
Labels: documentation

#782 [LLM Observability] Add new landing page
  images/llm-amazon-bedrock-guardrails.png
  images/llm-costs-usage-concerns.png
  images/llm-openai-applications.png
  images/llm-performance-reliability.png
  solutions/observability/apps.md
  solutions/observability/apps/llm-observability.md
  solutions/toc.yml
Labels: documentation

#1019 [D&M] Fixes typo on built-in role page
  deploy-manage/users-roles/cluster-or-deployment-auth/built-in-roles.md
Labels: documentation

#962 (Bug) Modify Index Template to LogsDB
  manage-data/data-store/data-streams/logs-data-stream.md
Labels: bug, supportability

#990 Adds instructions for customers to complete their AWS annual subscription registration
  deploy-manage/deploy/elastic-cloud/complete-registration-of-an-annual-subscription-on-aws-marketplace.md
  deploy-manage/images/aws-accept-prepaid-offer.png
  deploy-manage/images/aws-complete-registration.png
  deploy-manage/toc.yml
Labels: documentation

#713 [security][9.0] Creates Automatic Migrations guide
  images/security-siem-migration-1.png
  images/security-siem-migration-edit-rule.png
  images/security-siem-migration-processed-rules.png
  images/siem-migration-processed-rules.png
  solutions/security/get-started.md
  solutions/security/get-started/automatic-migration.md
  solutions/toc.yml
Labels: documentation, enhancement

#1024 Document how to configure Elastic Agent Add-On on Amazon EKS
  reference/fleet/images/elastic-agent-fleet.png
  reference/fleet/running-on-eks-managed-by-fleet.md
Labels: documentation, enhancement

#1035 [E&A] Pulls back EIS docs
  deploy-manage/cloud-organization/billing/elastic-observability-billing-dimensions.md
  explore-analyze/elastic-inference.md
  explore-analyze/elastic-inference/eis.md
  explore-analyze/elastic-inference/inference-api/elastic-inference-service-eis.md
  explore-analyze/toc.yml
  solutions/observability/observability-ai-assistant.md
  solutions/search/rag/playground.md
Labels: documentation

#1014 9.0 Security RN updates
  release-notes/elastic-security/breaking-changes.md
  release-notes/elastic-security/deprecations.md
  release-notes/elastic-security/index.md
  release-notes/elastic-security/known-issues.md
Labels: documentation

#1038 [AutoOps] Port doc updates from the Coud repo
  deploy-manage/images/cloud-autoops-deployment-resources.png
  deploy-manage/monitor/autoops/ec-autoops-deployment-view.md
Labels: documentation

#1054 Chore: Modify the upgrade docs to clarify the `user` and `pass` arguments
  deploy-manage/upgrade/orchestrator/upgrade-cloud-enterprise.md
Labels: documentation

#1064 Adds O11y 9.0.0 RNs
  release-notes/elastic-observability/breaking-changes.md
  release-notes/elastic-observability/deprecations.md
  release-notes/elastic-observability/index.md
  release-notes/elastic-observability/known-issues.md
  release-notes/elastic-observability/toc.yml
Labels: release-notes

#1059 Updates the Serverless changelog
  release-notes/elastic-cloud-serverless/deprecations.md
  release-notes/elastic-cloud-serverless/index.md
Labels: Serverless, release-notes

#920 [Detection Engine][Docs][9.0] New wording for frozen tier support
  solutions/security/detect-and-alert.md
Labels: documentation

#1095 Update links to ESQL reference docs
  explore-analyze/discover/try-esql.md
  explore-analyze/geospatial-analysis.md
  explore-analyze/query-filter/languages/esql-cross-clusters.md
  explore-analyze/query-filter/languages/esql-getting-started.md
  explore-analyze/query-filter/languages/esql-kibana.md
  explore-analyze/query-filter/languages/esql-multi-index.md
  manage-data/ingest/transform-enrich/set-up-an-enrich-processor.md
  solutions/search/esql-for-search.md
  solutions/search/esql-search-tutorial.md
  solutions/search/full-text.md
  solutions/search/full-text/how-full-text-works.md
  solutions/search/hybrid-semantic-text.md
  solutions/search/semantic-search/semantic-search-semantic-text.md
  solutions/security/detect-and-alert/create-detection-rule.md
  solutions/security/investigate/timeline.md
Labels: documentation

#985 Clean up OpenTelemetry content
  redirects.yml
  solutions/observability/apm/collect-metrics.md
  solutions/observability/apm/get-started-apm-server-binary.md
  solutions/observability/apm/get-started-fleet-managed-apm-server.md
  solutions/observability/apm/limitations.md
  solutions/observability/apm/managed-intake-service-event-api.md
  solutions/observability/apm/opentelemetry-intake-api.md
  solutions/observability/apm/resource-attributes.md
  solutions/observability/apm/traces.md
  solutions/observability/apm/transaction-sampling.md
  solutions/observability/apm/upstream-opentelemetry-collectors-language-sdks.md
  solutions/observability/apm/use-opentelemetry-with-apm.md
  solutions/observability/get-started.md
  solutions/observability/get-started/quickstart-monitor-hosts-with-opentelemetry.md
  solutions/observability/get-started/quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md
  solutions/observability/infra-and-hosts/understanding-no-results-found-message.md
  solutions/toc.yml
Labels: blocked

#1110 Adds note about max file size for get-file command
  solutions/security/endpoint-response-actions.md
Labels: documentation

#1093 Clarify ECH node bootlooping documentation
  troubleshoot/monitoring/node-bootlooping.md
Labels: documentation

#1118 Update links to ESQL reference docs
  explore-analyze/query-filter/languages/esql-getting-started.md
  explore-analyze/query-filter/languages/esql-kibana.md
Labels: documentation

#935 [Search] Drafts how to use OpenAI compatible models with the inference API
  solutions/_snippets/connect-local-llm-to-playground.md
  solutions/_snippets/use-local-llm-inference-api.md
  solutions/images/elasticsearch-openai-compatible-connector.png
  solutions/search/using-openai-compatible-models.md
  solutions/toc.yml
Labels: documentation, enhancement

#1117 Specifies Elastic 9.0 and Elastic Cloud Serverless on main release notes
  release-notes/intro/index.md
Labels: release-notes

#1130 Removes release dates from release notes
  release-notes/elastic-observability/deprecations.md
  release-notes/elastic-security/breaking-changes.md
  release-notes/elastic-security/deprecations.md
  release-notes/elastic-security/index.md
  release-notes/fleet-elastic-agent/breaking-changes.md
  release-notes/fleet-elastic-agent/deprecations.md
  release-notes/fleet-elastic-agent/index.md
  release-notes/fleet-elastic-agent/known-issues.md
Labels: release-notes

#1151 Replace hardcoded image links
  deploy-manage/deploy/elastic-cloud/create-serverless-project.md
  deploy-manage/images/64x64_Color_elasticsearch-logo-color-64px.png
  deploy-manage/images/64x64_Color_observability-logo-color-64px.png
  deploy-manage/images/64x64_Color_security-logo-color-64px.png
  get-started/images/64x64_Color_elasticsearch-logo-color-64px.png
  get-started/images/64x64_Color_observability-logo-color-64px.png
  get-started/images/64x64_Color_security-logo-color-64px.png
  get-started/index.md
Labels: documentation

#1162 [AutoOps] Remove extra column on the Nodes page
  deploy-manage/monitor/autoops/ec-autoops-nodes-view.md
Labels: documentation

#1163 [AutoOps] Remove extra column on the Indices page
  deploy-manage/monitor/autoops/ec-autoops-index-view.md
Labels: documentation

#1013 [Search] Removing GA notice from Semantic_reranker
  solutions/search/ranking/semantic-reranking.md
Labels: documentation

#1192 Updating documentation for semantic_reranking
  solutions/search/ranking/semantic-reranking.md
Labels: documentation

#1203 default-system-deployment-versions.md - Update system cluster versions
  deploy-manage/deploy/cloud-enterprise/default-system-deployment-versions.md
Labels: documentation

#1077 Fix sentence in elasticsearch-billing-dimensions
  deploy-manage/cloud-organization/billing/elasticsearch-billing-dimensions.md
Labels: documentation

#1124 update JWT realm docs to include at+jwt support
  deploy-manage/users-roles/cluster-or-deployment-auth/jwt.md
Labels: documentation, enhancement, v9.1.0

#1213 Update secure-connections.md - spacing issue.
  reference/fleet/secure-connections.md
Labels: documentation

#1142 Clarify OS & docker version sample during ECE upgrade
  deploy-manage/upgrade/orchestrator/upgrade-cloud-enterprise.md
Labels: documentation, supportability

#1230 Adds the Serverless changelog for April 21, 2025
  release-notes/elastic-cloud-serverless/index.md
Labels: Serverless

#1232 Fix superscripts in documentation
  deploy-manage/tools/snapshot-and-restore/read-only-url-repository.md
  deploy-manage/tools/snapshot-and-restore/shared-file-system-repository.md
  deploy-manage/tools/snapshot-and-restore/source-only-repository.md
  explore-analyze/query-filter/aggregations.md
Labels: documentation

#1221 Call out explicitly that we don't provide option to disable MFA
  cloud-account/multifactor-authentication.md
Labels: documentation, supportability

#1244 Creates UI copy request template
  .github/ISSUE_TEMPLATE/ui-copy-request.yaml
Labels: documentation

#1255 Updates the April 24, 2025 Serverless changelog
  release-notes/elastic-cloud-serverless/index.md
Labels: Serverless

#1256 Adds Wildcard DNS record disclaimers
  deploy-manage/deploy/cloud-enterprise/ece-wildcard-dns.md
Labels: Team:Platform

#1245 Updates LLM performance matrix
  solutions/security/ai/large-language-model-performance-matrix.md
Labels: documentation

#1271 Add doc for the modify data stream API
  manage-data/data-store/data-streams/modify-data-stream.md
Labels: documentation, Team:Platform

#1281 [E&A] Completes feature processors content
  explore-analyze/images/frequency-encoding.jpg
  explore-analyze/images/ngram-encoding.jpg
  explore-analyze/images/one-hot-encoding.jpg
  explore-analyze/images/target-mean-encoding.jpg
  explore-analyze/machine-learning/data-frame-analytics/ml-feature-processors.md
Labels: documentation, ml, Team:Search

#1282 [Search] Fixes link pointing to the semantic search with the inference API tutorial
  solutions/search/semantic-search.md
Labels: documentation, ml, nlp, Team:Search

#1285 Update skip_unavailable docs for ESQL
  explore-analyze/query-filter/languages/esql-cross-clusters.md
Labels: documentation, v8.19.0, v9.1.0, v9.0.1

#1016 [AutoOps] Update AWS regions availability
  deploy-manage/monitor/autoops/ec-autoops-regions.md
Labels: documentation

#1275 Clarify user authentication doc on ECH
  deploy-manage/users-roles/_snippets/external-realms.md
  deploy-manage/users-roles/cluster-or-deployment-auth/active-directory.md
  deploy-manage/users-roles/cluster-or-deployment-auth/ldap.md
  deploy-manage/users-roles/cluster-or-deployment-auth/pki.md
Labels: documentation, supportability

#1318 CSPM for GCP and Agentless integrations updates
  solutions/security/cloud/get-started-with-cspm-for-gcp.md
  solutions/security/get-started/agentless-integrations-faq.md
  solutions/security/get-started/agentless-integrations.md
  solutions/toc.yml
  troubleshoot/security.md
  troubleshoot/toc.yml
Labels: documentation
