Repository elastic/docs-content, pull requests merged in 2025-07, with the labels that each got.

#1599 Clarify the latest version of podman 5.2.2
  deploy-manage/deploy/cloud-enterprise/configure-host-rhel.md
  deploy-manage/deploy/cloud-enterprise/migrate-ece-to-podman-hosts.md
  deploy-manage/deploy/cloud-enterprise/migrate-to-podman-5.md
Labels: documentation, supportability

#1929 Rebuild onboarding docs (Get Started) for obs
  deploy-manage/deploy/elastic-cloud/create-serverless-project.md
  deploy-manage/deploy/elastic-cloud/serverless.md
  manage-data/ingest/ingest-reference-architectures/agent-to-es.md
  redirects.yml
  reference/observability/index.md
  solutions/images/Monitor_drill_down_1.png
  solutions/images/Monitor_drill_down_2.png
  solutions/images/Synthetic-Error_details.png
  solutions/images/observability-get-started.svg
  solutions/images/observability-quickstart-k8s-otel-entry-point.png
  solutions/images/observability-quickstart-monitor-hosts-otel-entry-point.png
  solutions/images/screenshot-observability-monitoring-k8s-kubernetes-logs-can-be-searched.png
  solutions/images/screenshot-observability-monitoring-k8s-kubernetes-overview-cluster.png
  solutions/images/screenshot-observability-monitoring-k8s-leverage-machine-learning-to-uncover-insights.png
  solutions/images/synth-monitors.png
  solutions/images/synthetics-create-browser-monitor.png
  solutions/observability.md
  solutions/observability/apm/get-started-serverless.md
  solutions/observability/applications/index.md
  solutions/observability/get-started.md
  solutions/observability/get-started/create-an-observability-project.md
  solutions/observability/get-started/get-started-with-dashboards.md
  solutions/observability/get-started/other-tutorials/add-data-from-splunk.md
  solutions/observability/get-started/other-tutorials/index.md
  solutions/observability/get-started/other-tutorials/tutorial-monitor-java-application.md
  solutions/observability/get-started/quickstart-collect-data-with-aws-firehose.md
  solutions/observability/get-started/quickstart-create-synthetic-monitor.md
  solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
  solutions/observability/get-started/quickstart-monitor-hosts-with-elastic-agent.md
  solutions/observability/get-started/quickstart-monitor-hosts-with-opentelemetry.md
  solutions/observability/get-started/quickstart-monitor-kubernetes-cluster-with-elastic-agent.md
  solutions/observability/get-started/quickstart-monitor-your-application-performance.md
  solutions/observability/get-started/quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md
  solutions/observability/get-started/quickstarts.md
  solutions/observability/get-started/what-is-elastic-observability.md
  solutions/observability/incident-management/service-level-objectives-slos.md
  solutions/observability/infra-and-hosts/get-started-with-system-metrics.md
  solutions/observability/logs/get-started-with-system-logs.md
  solutions/security/get-started/ingest-data-to-elastic-security.md
  solutions/toc.yml
Labels: documentation

#1919 [ESQL] Improve `skip_unavailable` description in CCS doc
  explore-analyze/query-filter/languages/esql-cross-clusters.md
Labels: documentation, v9.1.0

#1984 Clarify single email for MFA
  cloud-account/multifactor-authentication.md
Labels: documentation, supportability

#1995 Remove some links from Obs Get Started
  solutions/observability/get-started.md
Labels: documentation

#1893 Adds Rollup API examples to 'Get started with rollups using the API' page
  manage-data/lifecycle/rollup/getting-started-api.md
Labels: documentation, Team:Developer

#1728 Clarify index settings & APIs that are not available in serverless
  deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
Labels: documentation, Serverless, supportability

#1997 Adds 'Create or update synonyms set API examples' page
  solutions/search/full-text/create-update-synonyms-api-example.md
  solutions/search/full-text/search-with-synonyms.md
  solutions/toc.yml
Labels: documentation, Team:Developer

#1455 Edit Android and iOS links, redirects
  deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
  docset.yml
  redirects.yml
  solutions/observability/apm/api-keys.md
  solutions/observability/apm/apm-agent-central-configuration.md
  solutions/observability/apm/get-started-apm-server-binary.md
  solutions/observability/apm/get-started-fleet-managed-apm-server.md
  solutions/observability/apm/secret-token.md
  troubleshoot/observability/apm-agent-swift/apm-ios-agent.md
  troubleshoot/observability/apm.md
Labels: documentation

#2028 Update redirects.yml
  redirects.yml
Labels: bug

#2049 Clarify free instance description
  deploy-manage/cloud-organization/billing/billing-faq.md
Labels: documentation, supportability

#2042 [Security] Enable endpoint actions in events
  solutions/security/endpoint-response-actions.md
  solutions/security/endpoint-response-actions/isolate-host.md
Labels: v9.1.0

#2021 Clarify MinIO nonfunctional requirements
  deploy-manage/tools/snapshot-and-restore/s3-repository.md
Labels: documentation

#2053 Fix repeated word
  deploy-manage/tools/snapshot-and-restore/s3-repository.md
Labels: documentation

#1922 Add Elasticsearch semantic search quickstart
  docset.yml
  solutions/images/serverless-discover-semantic-esql.png
  solutions/images/serverless-discover-semantic.png
  solutions/search/get-started/quickstarts.md
  solutions/search/get-started/semantic-search.md
  solutions/toc.yml
Labels: Team:Projects

#2086 [Kibana][9.1 & Serverless] Update ML docs to reflect new nav
  explore-analyze/machine-learning/anomaly-detection/geographic-anomalies.md
  explore-analyze/machine-learning/anomaly-detection/mapping-anomalies.md
  explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-categories.md
  explore-analyze/machine-learning/anomaly-detection/ml-configuring-populations.md
  explore-analyze/machine-learning/anomaly-detection/ml-reverting-model-snapshot.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-classification.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-finding-outliers.md
  explore-analyze/machine-learning/data-frame-analytics/ml-dfa-regression.md
  explore-analyze/machine-learning/data-frame-analytics/ml-trained-models.md
  explore-analyze/machine-learning/nlp/ml-nlp-e5.md
  explore-analyze/machine-learning/nlp/ml-nlp-elser.md
  explore-analyze/machine-learning/nlp/ml-nlp-inference.md
  explore-analyze/machine-learning/setting-up-machine-learning.md
Labels: Serverless, v9.1.0, Team:Experience

#2081 Clarify vCPU boost doc
  deploy-manage/deploy/elastic-cloud/ec-vcpu-boost-instance.md
Labels: documentation, supportability

#1272 Update the docs about Journald support.
  reference/fleet/install-elastic-agents.md
Labels: Team:Ingest

#2039 Clarify hardware profile and instance configuration related docs for ECH
  deploy-manage/deploy/elastic-cloud/change-hardware.md
  deploy-manage/deploy/elastic-cloud/ec-change-hardware-profile.md
  deploy-manage/production-guidance/optimize-performance/indexing-speed.md
  deploy-manage/production-guidance/optimize-performance/search-speed.md
  deploy-manage/toc.yml
Labels: documentation, supportability

#1996 MinIO updates in ECE docs
  deploy-manage/deploy/cloud-enterprise/add-custom-bundles-plugins.md
  deploy-manage/images/cloud-enterprise-ece-minio-deployment.png
  deploy-manage/images/cloud-enterprise-ece-minio-large-arch.png
  deploy-manage/images/cloud-enterprise-ece-minio-repository.png
  deploy-manage/tools/snapshot-and-restore/cloud-enterprise.md
  deploy-manage/tools/snapshot-and-restore/manage-snapshot-repositories.md
  deploy-manage/tools/snapshot-and-restore/minio-on-premise-repository.md
Labels: ece

#1923 Augment vector search tutorial with getting started content
  solutions/search/get-started/quickstarts.md
  solutions/search/vector/bring-own-vectors.md
Labels: Team:Projects

#2142 Adds the Serverless changelog for July 15, 2025
  release-notes/elastic-cloud-serverless/index.md
Labels: Serverless, release-notes

#2165 Create alert rules directly from ESQL panel
  explore-analyze/images/esql-panel-create-rule.png
  explore-analyze/visualize/esorql.md
Labels: documentation

#2181 Add docs for async stop command
  explore-analyze/query-filter/languages/esql-rest.md
Labels: documentation

#2214 Security 9.0.4 release notes fix
  release-notes/elastic-security/index.md
Labels: release-notes

#2209 Update script-fields-api.md
  explore-analyze/scripting/script-fields-api.md
Labels: documentation, v9.1.0, Team:Developer, v9.2.0, v9.0.3

#2224 Updates 'Trained model autoscaling' page for Serverless adaptive resources behavior
  deploy-manage/autoscaling/trained-model-autoscaling.md
  deploy-manage/images/machine-learning-ml-nlp-deployment-id-elser-v2.png
  deploy-manage/images/ml-nlp-deployment-id-elser.png
Labels: documentation, Team:Developer

#2231 Updates screenshots about the process of starting a trained model
  explore-analyze/images/machine-learning-ml-nlp-deployment-id-elser-v2.png
  explore-analyze/images/ml-nlp-deployment-id-elser.png
  explore-analyze/machine-learning/nlp/ml-nlp-deploy-model.md
  explore-analyze/machine-learning/nlp/ml-nlp-elser.md
Labels: documentation, Team:Developer

#2023 [Security] [July 22] Attack Discovery scheduling and saved discoveries
  solutions/images/security-attack-discovery-settings.png
  solutions/images/security-attck-disc-example-disc.png
  solutions/images/security-attck-disc-select-model-empty.png
  solutions/security/ai/attack-discovery.md
Labels: Serverless, v9.1.0

#2290 [Security] Moves Automatic Migration from preview to GA
  solutions/security/get-started/automatic-migration.md
Labels: Serverless, v9.1.0

#2191 [Security] Entity Analytics: overview and privileged user monitoring
  solutions/security/advanced-entity-analytics.md
  solutions/security/advanced-entity-analytics/asset-criticality.md
  solutions/security/advanced-entity-analytics/entity-store.md
  solutions/security/advanced-entity-analytics/monitor-privileged-user-activitites.md
  solutions/security/advanced-entity-analytics/overview.md
  solutions/security/advanced-entity-analytics/privileged-user-monitoring-requirements.md
  solutions/security/advanced-entity-analytics/privileged-user-monitoring-setup.md
  solutions/security/advanced-entity-analytics/privileged-user-monitoring.md
  solutions/security/advanced-entity-analytics/view-analyze-risk-score-data.md
  solutions/security/advanced-entity-analytics/view-entity-details.md
  solutions/security/get-started/configure-advanced-settings.md
  solutions/security/get-started/elastic-security-ui.md
  solutions/toc.yml
Labels: v9.1.0

#1822 Edits for Central Management for EDOT SDKs
  solutions/observability/apm/apm-agent-central-configuration.md
  solutions/observability/apm/collect-application-data.md
  solutions/observability/apm/configure-apm-agent-central-configuration.md
  solutions/observability/apm/edot-sdks-central-configuration.md
  solutions/toc.yml
Labels: documentation, v9.1.0

#2293 [Security] Event collection updates for macOS
  solutions/images/security-event-collection.png
Labels: Serverless, v9.1.0

#2302 Fleet Server / Elastic Agent 9.1.0 release notes
  release-notes/fleet-elastic-agent/deprecations.md
  release-notes/fleet-elastic-agent/index.md
Labels: v9.1.0

#2019 [ECK] Update documentation for 3.1.0
  deploy-manage/deploy/cloud-on-k8s.md
  deploy-manage/deploy/cloud-on-k8s/configuration-fleet.md
  deploy-manage/deploy/cloud-on-k8s/propagate-labels-annotations.md
  deploy-manage/toc.yml
  reference/fleet/advanced-kubernetes-managed-by-fleet.md
Labels: v9.1.0, eck

#2315 Support knn filter on nested metadata
  solutions/search/vector/knn.md
Labels: v9.2.0

#2337 Fix rows in differences between deploy modes
  deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
Labels: documentation

#2113 Creates content connectors page in security docs
  solutions/security/get-started/content-connectors.md
  solutions/toc.yml
Labels: documentation, Team:Security
